### ISSUE TITLE
Tags don't work in reading mode

### ISSUE THREAD

**Issue by Weirwynn** [binarynoir/obsidian-markdown-tags#2]
I like the idea and the syntax, but the tags revert to plain text in reading mode, which also means they revert to plain text in the canvas as soon as you click away from an item.

**Comment by kryptonianson** [comment]
I will look into this right away. Thank you for the report.

**Comment by kryptonianson** [comment]
Thank you again for the feedback. I have added support for reading mode. I hope you enjoy the latest release!
