### ISSUE TITLE
Conflict with callout rendering

### ISSUE THREAD

**Issue by viktors31** [binarynoir/obsidian-markdown-tags#3]
Hello binarynoir,
I am a new user in Obsidian. I started work with your plugin. I like it.
But I have note with callout (https://help.obsidian.md/Editing+and+formatting/Callouts from official site)
And, I got trouble. When I'm using ur plugin, my callouts are rendering wrong. Dissapears callout icon and title font style (it is bold as rule). Look on pictures.
![callout_fail](https://github.com/user-attachments/assets/a59efade-2b8d-4b2f-bdbe-61bdf23e0a6f)
![callout_orig](https://github.com/user-attachments/assets/fc26aadf-fa91-4b82-b1df-960e403a6516)

**Comment by viktors31** [comment]
I'm not frontend developer or expert.
But I lauch DevTools and found, what div element redrawing in script. And div.callout also. I could localize error.
And I paste in done JS file from plugin on my computer some code to fix that.
Also this is a classic workaround. But it is done for me!

In JS function which takes elements from DOM and replace constructions (I guess it would work only for ((tag and etc..) I paste the condition: if classList array of current element from each contains "callout" then just return (break code running). But also I had to paste check on not null classList because I touched clean JS which return me a error during attempt to get undefined and crashes my obsidian.

```
viewModeTagsHighlighter() {
            return (e, o) => {
                Array.from(e.querySelectorAll("p, li, span, div")).forEach(n => {
                    var p;
                    let d = n.textContent;
                    console.log(n.classList[0]);
                    /*if((n.classList !== null)||(n.classList[0].contains("callout")))return;*/
                    if (!d)
                        return;
                    let a, g = d;
                    for (; (a = D.exec(d)) !== null; ) {
                        let {label: r="", bgcolor: b="", fgcolor: s=""} = (p = a.groups) != null ? p : {}
                          , u = $(r)
                          , i = b && w(b) ? b : ""
                          , l = s && w(s) ? s : ""
                          , h = a[0].startsWith("((<")
                          , C = k(u, i, l, h)
                          , y = `<span class="${C.spec.class}" style="${C.spec.attributes.style}">${u}</span>`;
                        g = g.replace(a[0], y)
                    }
                    n.innerHTML = g
                }
                )
            }
        }
```

**Comment by viktors31** [comment]
P.S: Using last version of the plugin and fresh obsidian (1.7.5)

**Comment by kryptonianson** [comment]
Thank you so much for the report. I will take a look as soon as possible and see what is wrong.

**Comment by kryptonianson** [comment]
I have a solution. Sorry it took a bit longer than I hoped as I had to cover some other related editing issues with callouts. Your sample code was very helpful and I thank you so much for using my plugin. I plan on expanding its features soon. I will post a new release within the hour. Thank you again.

**Comment by kryptonianson** [comment]
Release 1.2.1 has been released and fixes this issue. Please feel free to open a new issue if you see any other problems. Thank you again for helping me make this product better.
