### ISSUE TITLE
Breaks links in Reading Mode

### ISSUE THREAD

**Issue by chadlipscomb** [binarynoir/obsidian-markdown-tags#5]
In Reading mode, Markdown and Wikilinks display as standard text and are not clickable. 
Disabling this plugin fixes it.

**Comment by kryptonianson** [comment]
Thank you so much for taking the time to report this issue. I am working on a fix for this and one other related bug. I will update you as soon as it is available. Again thank you for your valuable time and your patience.

**Comment by kryptonianson** [comment]
I am very happy to let you know I have fixed the issue version 1.2.3 and things should work much better. I want to thank you again for your kind patience and for helping me make the extension better. Please open a ticket if you find any other issues.
